In [2]:
import pandas
import numpy
from sklearn.preprocessing import StandardScaler , KBinsDiscretizer
from sklearn.impute import SimpleImputer
import seaborn as sns
import scipy.stats as stats
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

pandas.set_option('display.max_columns', None)
pandas.set_option('display.max_rows', None)

In [5]:
df = pandas.read_csv('https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day33-handling-mixed-variables/titanic.csv')
print(df.shape)
df.head()

(891, 4)

  Cabin            Ticket number  Survived
0   NaN         A/5 21171      5         0
1   C85          PC 17599      3         1
2   NaN  STON/O2. 3101282      6         1
3  C123            113803      3         1
4   NaN            373450      A         0

In [12]:
df['number'].value_counts()
df['number_numeric'] = pandas.to_numeric(df['number'], errors='coerce', downcast='integer')
df['number_categoric'] = numpy.where(df['number_numeric'].isnull(), df['number'], 'NaN')

df['number_numeric'] = df['number_numeric'].fillna(0)
df.head()

  Cabin            Ticket number  Survived  number_numeric number_categoric
0   NaN         A/5 21171      5         0             5.0              NaN
1   C85          PC 17599      3         1             3.0              NaN
2   NaN  STON/O2. 3101282      6         1             6.0              NaN
3  C123            113803      3         1             3.0              NaN
4   NaN            373450      A         0             0.0                A