In [35]:
#For encoding ordianl data we use ordinal encoding and for nomial data we use one hot encoding
import pandas as pd
import matplotlib.pyplot as plt
import seaborn
from sklearn.preprocessing import OrdinalEncoder , LabelEncoder

data = {
    'Customer_ID': [101, 102, 103, 104, 105],
    'Education_Level': ['High School', 'Bachelor', 'PhD', 'Master', 'Bachelor'],
    'Satisfaction': ['Low', 'Medium', 'High', 'Low', 'High'],
    'Churned': ['No', 'Yes', 'No', 'No', 'Yes']
}

df = pd.DataFrame(data)
df = df.set_index('Customer_ID')

df.head()

            Education_Level Satisfaction Churned
Customer_ID
101             High School          Low      No
102                Bachelor       Medium     Yes
103                     PhD         High      No
104                  Master          Low      No
105                Bachelor         High     Yes

In [36]:
#LABEL ENCODING - if the output data is categorical then we use this..
label_enc = LabelEncoder()
df['Churned'] = label_enc.fit_transform(df['Churned'])
#---both works same but while using sklearn this is the differnece

#ORDINAL ENCODING - if their we have to change in the input data then we use ordinal encoding we transform the data to the numerical text in order to get the output
enc = OrdinalEncoder(categories=[['Low' , 'Medium' , 'High'] , ['High School', 'Bachelor', 'Master', 'PhD']])
df[['Satisfaction' , 'Education_Level']] = enc.fit_transform(df[['Satisfaction', 'Education_Level']])

In [37]:
df.head()

             Education_Level  Satisfaction  Churned
Customer_ID
101                      0.0           0.0        0
102                      1.0           1.0        1
103                      3.0           2.0        0
104                      2.0           0.0        0
105                      1.0           2.0        1